language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
  - sudo apt-get update  -qq
  - sudo apt-get install -qq ffmpeg rtmpdump swftools 
install: 
  - "pip install -r requirements.txt --use-mirrors"
script: 
  - export PYTHONPATH=.:$PYTHONPATH
  - nosetests
